In [2]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
# bo'sh qiymatlarni tekshiramiz
df.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [9]:
# yangi hisob-toifasi ustuni yaratamiz
df["HisobToifasi"] = df["total_bill"].apply(lambda x: "Arzon" if x<20 else ("O'rta" if x<40 else "Qimmat"))
df

     total_bill   tip     sex smoker   day    time  size HisobToifasi
0         16.99  1.01  Female     No   Sun  Dinner     2        Arzon
1         10.34  1.66    Male     No   Sun  Dinner     3        Arzon
2         21.01  3.50    Male     No   Sun  Dinner     3        O'rta
3         23.68  3.31    Male     No   Sun  Dinner     2        O'rta
4         24.59  3.61  Female     No   Sun  Dinner     4        O'rta
..          ...   ...     ...    ...   ...     ...   ...          ...
239       29.03  5.92    Male     No   Sat  Dinner     3        O'rta
240       27.18  2.00  Female    Yes   Sat  Dinner     2        O'rta
241       22.67  2.00    Male    Yes   Sat  Dinner     2        O'rta
242       17.82  1.75    Male     No   Sat  Dinner     2        Arzon
243       18.78  3.00  Female     No  Thur  Dinner     2        Arzon

[244 rows x 8 columns]

In [15]:
# choychaqa foizini hisoblovchi yangi ustun yaratamiz
df["Foiz"] = df["tip"] / df["total_bill"] * 100
df

,total_bill,tip,sex,smoker,day,time,size,HisobToifasi,Foiz
0,16.99,1.01,Female,No,Sun,Dinner,2,Arzon,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,Arzon,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,O'rta,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,O'rta,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,O'rta,14.680765
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,O'rta,20.392697
240,27.18,2.00,Female,Yes,Sat,Dinner,2,O'rta,7.358352
241,22.67,2.00,Male,Yes,Sat,Dinner,2,O'rta,8.822232
242,17.82,1.75,Male,No,Sat,Dinner,2,Arzon,9.820426
243,18.78,3.00,Female,No,Thur,Dinner,2,Arzon,15.974441

In [31]:
# kun bo'yicha o'rtacha choychaqa foizini topamiz
# natijani kamayish tartibida joylashtiramiz
df.pivot_table(values="Foiz", index="day", aggfunc="mean").sort_values("Foiz", ascending=False)

           Foiz
day
Fri   16.991303
Sun   16.689729
Thur  16.127563
Sat   15.315172

In [30]:
# Erkaklar va ayollar qoldiradigan o'rtacha choychaqa farini tekshiramiz
df.pivot_table(values="tip", index="sex", aggfunc="mean")

             tip
sex
Female  2.833448
Male    3.089618

In [34]:
# chekuvchi/chekmaydigan, kun bo'yicha buyurtmalar sonini tekshiramiz
df.pivot_table(values="total_bill", index="day", columns="smoker", aggfunc="count")

smoker  No  Yes
day
Fri      4   15
Sat     45   42
Sun     57   19
Thur    45   17

In [41]:
# eng yuqori choychaqa foizini (Foiz ustuni) bergan 5 ta mijozning barcha ma'lumotlarini topamiz
# Foiz ustunini yuqoridan pastga saralaymiz. eng yuqorida eng katta qiymat qoladi
df.sort_values("Foiz", ascending=False).head()

,total_bill,tip,sex,smoker,day,time,size,HisobToifasi,Foiz
172,7.25,5.15,Male,Yes,Sun,Dinner,2,Arzon,71.034483
178,9.60,4.00,Female,Yes,Sun,Dinner,2,Arzon,41.666667
67,3.07,1.00,Female,Yes,Sat,Dinner,1,Arzon,32.573290
232,11.61,3.39,Male,No,Sat,Dinner,2,Arzon,29.198966
183,23.17,6.50,Male,Yes,Sun,Dinner,4,O'rta,28.053517