In [5]:
from google.colab import files
uploaded = files.upload()

Saving final_data_2023.csv to final_data_2023.csv

In [6]:
import pandas as pd
df = pd.read_csv("final_data_2023.csv")
df = df.drop(columns=["Unnamed: 0"])
df.head()

,iso_3,continent,country,year,rate,gdp,oecd,eu27,gseven,gtwenty,brics
0,AFG,AS,Afghanistan,2023,20.0,14.868619,0,0,0,0,0
1,AGO,AF,Angola,2023,25.0,111.183931,0,0,0,0,0
2,ALB,EU,Albania,2023,15.0,14.543382,0,0,0,0,0
3,ARE,AS,United Arab Emirates,2023,9.0,413.482549,0,0,0,0,0
4,ARG,SA,Argentina,2023,35.0,579.238431,0,0,0,1,0

In [ ]:
df.describe()

,year,rate,gdp,oecd,eu27,gseven,gtwenty,brics
count,181.0,181.000000,181.000000,181.000000,181.000000,181.000000,181.000000,181.000000
mean,2023.0,23.452746,503.940131,0.209945,0.149171,0.038674,0.104972,0.027624
std,0.0,7.455302,2120.912786,0.408399,0.357245,0.193352,0.307368,0.164349
min,2023.0,0.000000,0.401493,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2023.0,20.000000,13.749928,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2023.0,25.000000,51.857006,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2023.0,30.000000,263.504087,0.000000,0.000000,0.000000,0.000000,0.000000
max,2023.0,37.500000,21503.528547,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
yaqin_sharq = df[df['country'].isin(["United Arab Emirates", "Saudi Arabia", "Qatar", "Kuwait", "Bahrain", "Oman"])]
yaqin_sharq

,iso_3,continent,country,year,rate,gdp,oecd,eu27,gseven,gtwenty,brics
3,ARE,AS,United Arab Emirates,2023,9.0,413.482549,0,0,0,0,0
16,BHR,AS,Bahrain,2023,0.0,35.699699,0,0,0,0,0
91,KWT,AS,Kuwait,2023,15.0,115.719309,0,0,0,0,0
126,OMN,AS,Oman,2023,15.0,78.866854,0,0,0,0,0
136,QAT,AS,Qatar,2023,10.0,186.647040,0,0,0,0,0
140,SAU,AS,Saudi Arabia,2023,20.0,736.659341,0,0,0,1,0

In [ ]:
# task_1 gdp ustuni bo'yicha eng yuqori 5 ta mamlakatni toping (eng boy mamlakatlar).
df.sort_values("gdp", ascending = False).head(5)

,iso_3,continent,country,year,rate,gdp,oecd,eu27,gseven,gtwenty,brics
170,USA,NO,United States of America,2023,25.768,21503.528547,1,0,1,1,0
31,CHN,AS,China,2023,25.000,17325.917708,0,0,0,1,1
84,JPN,AS,Japan,2023,29.740,4592.771102,1,0,1,1,0
42,DEU,EU,Germany,2023,29.941,3659.626758,1,1,1,1,0
58,GBR,EU,United Kingdom of Great Britain and Northern I...,2023,25.000,3164.425551,1,0,1,1,0

In [ ]:
# task_2 gdp ustuni bo'yicha eng past 5 ta mamlakatni toping (eng kambag'al mamlakatlar, ya'ni GDP eng kichik).
df.sort_values("gdp").head(5)

,iso_3,continent,country,year,rate,gdp,oecd,eu27,gseven,gtwenty,brics
148,STP,AF,Sao Tome and Principe,2023,25.0,0.401493,0,0,0,0,0
161,TON,OC,Tonga,2023,25.0,0.433823,0,0,0,0,0
44,DMA,NO,Dominica,2023,25.0,0.521037,0,0,0,0,0
176,WSM,OC,Samoa,2023,27.0,0.794835,0,0,0,0,0
172,VCT,NO,Saint Vincent and the Grenadines,2023,28.0,0.820678,0,0,0,0,0

In [7]:
# task_3 rate ustuni bo'yicha saralab, natijadan faqat country va rate ustunlarini ko'rsating (butun jadval emas, faqat shu ikkita ustun):
saralangan = df.sort_values("rate")
saralangan[["country", "rate"]]

         country  rate
17       Bahamas   0.0
20        Belize   0.0
16       Bahrain   0.0
175      Vanuatu   0.0
23      Barbados   5.5
..           ...   ...
110        Malta  35.0
156         Chad  35.0
141        Sudan  35.0
149     Suriname  36.0
133  Puerto Rico  37.5

[181 rows x 2 columns]

In [ ]:
# task_4 Ikkita shartni birlashtiring — avval continent == "AS" (Osiyo) bo'yicha filtrlang, so'ng natijani rate bo'yicha kamayish tartibida saralang, va faqat birinchi 5 tasini ko'rsating.
osiyo = df[df["continent"] == "AS"]
osiyo_saralangan = osiyo.sort_values("rate", ascending=False).head(5)
osiyo_saralangan

,iso_3,continent,country,year,rate,gdp,oecd,eu27,gseven,gtwenty,brics
75,IND,AS,India,2023,30.00,3122.477069,0,0,0,1,1
97,LKA,AS,Sri Lanka,2023,30.00,93.835513,0,0,0,0,0
84,JPN,AS,Japan,2023,29.74,4592.771102,1,0,1,1,0
127,PAK,AS,Pakistan,2023,29.00,353.211850,0,0,0,0,0
155,SYR,AS,Syrian Arab Republic,2023,28.00,19.829067,0,0,0,0,0

In [ ]:
# task_5 Har bir qit'a bo'yicha o'rtacha gdp ni hisoblang.
df.groupby("continent")["rate"].mean()

continent
AF    27.365882
AS    19.802979
EU    19.924846
NO    25.457417
OC    23.750000
SA    28.375000
Name: rate, dtype: float64

In [ ]:
# task_6 Har bir qit'ada nechta mamlakat borligini sanang (.count() yoki .size() ishlatib ko'ring, ikkalasini ham sinab, farqini payqang).
df.groupby("continent")["country"].count()

continent
AF    51
AS    47
EU    39
NO    24
OC     8
SA    12
Name: country, dtype: int64

In [ ]:
df.groupby("continent")["country"].size()

continent
AF    51
AS    47
EU    39
NO    24
OC     8
SA    12
Name: country, dtype: int64

In [9]:
# task_7 .agg() yordamida, har bir qit'a uchun rate ustunining mean, min, max larini bitta jadvalda ko'rsating:
df.groupby("continent")["rate"].agg(["mean","min", "max"])

                mean   min   max
continent
AF         27.365882  15.0  35.0
AS         19.802979   0.0  30.0
EU         19.924846   9.0  35.0
NO         25.457417   0.0  37.5
OC         23.750000   0.0  30.0
SA         28.375000  10.0  36.0

In [13]:
# task_8 faqat oecd == 1 bo'lgan mamlakatlarni filtrlang, so'ng ularni continent bo'yicha guruhlab, o'rtacha rate ni toping.
saralangan_oecd = df[df['oecd'] == 1]
saralangan_oecd.groupby("continent")["rate"].mean()

continent
AS    26.060000
EU    21.752654
NO    27.994500
OC    29.000000
SA    31.000000
Name: rate, dtype: float64

In [14]:
df.groupby("continent")["rate"].mean()

continent
AF    27.365882
AS    19.802979
EU    19.924846
NO    25.457417
OC    23.750000
SA    28.375000
Name: rate, dtype: float64